---
# Download image
- name: Download file with check (sha256)
  ansible.builtin.get_url:
    url: https://cios.dhitechnical.com/C9200_9300_9400_9500_9600/C9800-SW-iosxe-wlc.17.08.01.SPA.bin
    dest: "./{{ desired_ios_image }}"
  delegate_to: localhost
  run_once: true

# Copy it to device flash.
- name: Copy the ios image into the network device
  ansible.netcommon.net_put:
    src: "./{{ desired_ios_image }}"
    dest: "flash:{{ desired_ios_image }}"
  vars:
    ansible_command_timeout: 3600

- name: Check if the image is already present on the flash
  cisco.ios.ios_command:
    commands: 'show flash: | include {{ desired_ios_image  }}'
  register: flash_info

- name: Debug var
  # Content suggestion provided by Ansible Lightspeed
  ansible.builtin.debug:
    msg: "{{ flash_info.stdout }}"