---
- name: Upgrade Cisco IOS devices
  hosts: cisco
  gather_facts: false

  vars:
    ansible_network_cli_ssh_type: paramiko
    desired_ios_image: c8000v-universalk9.17.07.01a.SPA.bin

  pre_tasks:
    # Gather information (facts)
    - name: Gather facts from cisco ios devices
      # Content suggestion provided by Ansible Lightspeed
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Show current cisco ios devices version
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items:
        - "The current IOS version is: {{ ansible_net_version }}"
        - "The IOS type is: {{ ansible_net_iostype }}"

    # - name: Check boot path
    #   cisco.ios.ios_command:
    #     commands: 'show boot'
    #   register: results

    # - name: Debug previous results output
    #   # Content suggestion provided by Ansible Lightspeed
    #   ansible.builtin.debug:
    #     msg: "{{ results.stdout }}"

    # - name: Check availability of flashs
    #   cisco.ios.ios_command:
    #     commands: "show file systems | include flash"
    #   register: flash_values

    # - name: debug flash_values from previous tasks
    #   # Content suggestion provided by Ansible Lightspeed
    #   ansible.builtin.debug:
    #     msg: "{{ flash_values.stdout }}"

    - name: Check if the image is already present on the flash
      cisco.ios.ios_command:
        commands: 'show flash: | include {{ desired_ios_image  }}'
      register: flash_info

    - name: Debug var
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        msg: "{{ flash_info.stdout }}"

  tasks:
    # Perform a backup before to upgrade
    - name: Backup cisco ios config device
      # It will create a backup file called <hostname>_config.<current-date>@<current-time>
      cisco.ios.ios_config:
        backup: true

    - name: Copies the contents of the image and the package to the software repository. File location may be local or remote.
      cisco.ios.ios_command:
        commands:
          - command: "install add file bootflash:{{ desired_ios_image }}"
            prompt: 'confirm'
            answer: yes
      vars:
        ansible_command_timeout: 60
      ignore_errors: true
    
    # - name: Fail only when the error in the previous task failed is not because the file is already added
    #   # Content suggestion provided by Ansible Lightspeed
    #   ansible.builtin.fail:
    #     msg: The file is already added to the flash
    #   when: "'Super package already added' not in flash_info.stdout"

    - name: Provides an overview of the image versions and their corresponding install state.
      cisco.ios.ios_command:
        commands: 'show install summary'
      register: install_summary

    - name: Debug install summary
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        msg: "{{ install_summary.stdout_lines }}"

    - name: Activates the previously added package and reloads the platform.
      cisco.ios.ios_command:
        commands:
          - command: "install activate auto-abort-timer 120"
            prompt: 'reload'
            answer: yes
      vars:
        ansible_command_timeout: 3600

    # # Reload device
    # - name: Reload cisco ios device
    #   # Content suggestion provided by Ansible Lightspeed
    #   cisco.ios.ios_command:
    #     commands:
    #       - command: "reload"
    #         prompt: 'confirm'
    #         answer: 'y'
    #   vars:
    #     ansible_command_timeout: 360
    
    - name: Reset connection to the switch
      ansible.builtin.meta: reset_connection

    # Wait for device to become available again
    - name: Wait for the cisco ios device to become alive again
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.wait_for:
        port: 22
        host: "{{ ansible_host }}"
        delay: 240
        timeout: 1800
      delegate_to: localhost
      connection: local

  post_tasks:
    # Gather information (facts)
    - name: Gather facts from cisco ios devices
      # Content suggestion provided by Ansible Lightspeed
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Show new cisco ios devices version
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - "The new IOS version is: {{ ansible_net_version }}"
        - "The IOS type is: {{ ansible_net_iostype }}"