- name: Gather facts from aruba devices
  hosts: all

  tasks:
    - name: Retrieve all information from the device and save into a variable "facts_output".
      rubanetworks.aoscx.aoscx_facts:
      register: facts_output